- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  become: true
  tasks:
    - name: do nothing
      command: /bin/true
    - git:
        # repo: git@github.com:cyeun/flaskr.git
        repo: https://github.com/cyeun/flaskr.git
        dest: /srv/nodeinfra
        accept_hostkey: true
    - name: Install git
      dnf:
        name: git
        state: present

